# Generated by Django 3.2.12 on 2022-04-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
        ('mindspace', '0011_auto_20220405_1119'),
        ('profiles', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qna.answer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject_mindspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mindspace.mindspace'),
        ),
    ]
