# Generated by Django 3.2.12 on 2022-03-18 06:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 18, 6, 49, 38, 145370, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mindspace',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='mindspace.mindspace')),
            ],
        ),
    ]
