# Generated by Django 3.2.12 on 2022-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220403_1853'),
        ('mindspace', '0008_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindspace',
            name='commenters',
            field=models.ManyToManyField(null=True, related_name='can_comment', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='mindspace',
            name='editors',
            field=models.ManyToManyField(null=True, related_name='can_edit', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='mindspace',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mindspace',
            name='viewers',
            field=models.ManyToManyField(null=True, related_name='can_view', to='profiles.Profile'),
        ),
    ]
