# Generated by Django 3.2.12 on 2022-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220403_1853'),
        ('mindspace', '0009_auto_20220404_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindspace',
            name='commenters',
            field=models.ManyToManyField(related_name='can_comment', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='mindspace',
            name='editors',
            field=models.ManyToManyField(related_name='can_edit', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='mindspace',
            name='viewers',
            field=models.ManyToManyField(related_name='can_view', to='profiles.Profile'),
        ),
    ]
