# Generated by Django 3.2.12 on 2022-04-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0010_auto_20220404_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='mindspace/resource_document'),
        ),
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mindspace/resource_image'),
        ),
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='res_format',
            field=models.CharField(choices=[('Video', 'Video'), ('Image', 'Image'), ('Document', 'Document'), ('Quote', 'Quote'), ('Link', 'Link to external source')], default='Link', max_length=8),
        ),
        migrations.AddField(
            model_name='resource',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='mindspace/resource_video'),
        ),
    ]
