# Generated by Django 3.2.12 on 2022-04-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0013_alter_sharemindspace_mindspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharemindspace',
            name='shared_with_info',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
