# Generated by Django 3.2.12 on 2022-04-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0014_sharemindspace_shared_with_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mindspace',
            name='commenters',
        ),
        migrations.RemoveField(
            model_name='mindspace',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='mindspace',
            name='viewers',
        ),
    ]
