# Generated by Django 3.2.13 on 2022-04-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20220410_1628'),
        ('mindspace', '0016_alter_sharemindspace_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='description',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AddField(
            model_name='note',
            name='written_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='written_notes', to='profiles.profile'),
        ),
    ]
