# Generated by Django 3.2.13 on 2022-04-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20220410_1628'),
        ('mindspace', '0017_auto_20220422_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_notes', to='profiles.profile'),
        ),
    ]
