# Generated by Django 3.2.12 on 2022-04-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_auto_20220403_1853'),
        ('mindspace', '0011_auto_20220405_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('asked_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='profiles.profile')),
                ('tagged_mindspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mindspace_questions', to='mindspace.mindspace')),
                ('tagged_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_questions', to='mindspace.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('replied_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_answers', to='profiles.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qna.question')),
                ('tagged_mindspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mindspace_answers', to='mindspace.mindspace')),
                ('tagged_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_answers', to='mindspace.resource')),
            ],
        ),
    ]
