# Generated by Django 3.2.12 on 2022-03-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_created_by'),
        ('mindspace', '0003_mindspace_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindspace',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mindspaces', to='profiles.profile', unique=True),
        ),
    ]
