# Generated by Django 3.2.12 on 2022-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0006_alter_mindspace_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindspace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
