# Generated by Django 3.2.12 on 2022-04-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0012_sharemindspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemindspace',
            name='mindspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='mindspace.mindspace'),
        ),
    ]
