# Generated by Django 3.2.13 on 2022-05-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0018_alter_note_written_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sharemindspace',
            name='access_level',
            field=models.CharField(choices=[('viewer', 'VIEW'), ('editor', 'EDIT')], max_length=9),
        ),
    ]
