# Generated by Django 3.2.13 on 2022-06-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_notification_notification_type'),
        ('mindspace', '0019_auto_20220530_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources_created', to='profiles.profile'),
        ),
    ]
