# Generated by Django 3.2.13 on 2022-06-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_notification_notification_type'),
        ('mindspace', '0020_resource_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharemindspace',
            old_name='mindspace',
            new_name='shared_mindspace',
        ),
        migrations.AlterUniqueTogether(
            name='sharemindspace',
            unique_together={('shared_mindspace', 'shared_with')},
        ),
    ]
